bump_version: null
lint: null
nf_core_version: 3.0.0
org_path: null
repository_type: pipeline
template:
  author: Payam Emami
  description: Pre-processing of mass spectrometry-based metabolomics data
  force: false
  is_nfcore: true
  name: metaboigniter
  org: nf-core
  outdir: .
  skip_features: null
  version: 2.1.0dev
update: null
