nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: Payam Emami
  description: Pre-processing of mass spectrometry-based metabolomics data
  force: false
  is_nfcore: true
  name: metaboigniter
  org: nf-core
  outdir: .
  version: 2.1.0dev
